# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea3edacea3701ecbe1afd5524724b3a623cd5e60bf37f3083004fdcb8b4ec9eb2366510ccdb63ebd5ed721b7f34b2d6a7fab0e68e83e273a6f87bf436d5ddfcd

test:
  secret_key_base: b60ce596abb16da7468bf748d128257f3c1d72b67c821bf05fc8d114160fc24f69ed451deb80d8c84653dc804a6bd74fa272ef11fe779e43c052f80c7cfb7a93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
